FROM python:3.12-slim

# Create user name and home directory variables. 
# The variables are later used as $USER and $HOME. 
ENV USER=user
ENV HOME=/home/$USER

# Add user to system
RUN useradd -m -u 1000 $USER

# Set working directory (this is where the code should go)
WORKDIR $HOME

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# RUN /bin/bash -c "apt update"
# RUN /bin/bash -c "curl https://dl.min.io/client/mc/release/linux-amd64/mc --output mc && chmod +x mc"
COPY requirements.txt $HOME/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY serve.py $HOME/serve.py
COPY deploy.sh $HOME/deploy.sh
COPY deploy.sh $HOME/start-script.sh
COPY tests/model/ $HOME/models/
RUN chmod +x start-script.sh \
    && chmod +x deploy.sh \
    && chown -R $USER:$USER $HOME

WORKDIR $HOME/models
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR $HOME
ENV STACKN_MODEL_PATH=$HOME/models
ENV PYTHONPATH=$HOME/models

CMD ["./deploy.sh"]
