FROM ubuntu:latest

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    software-properties-common \
    git \
    git-lfs \
    python3 \
    python3-pip \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install code-server
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Create user and enforce umask system-wide
RUN useradd -u 1001 -g 1000 -m serve && \
    chown -R serve:1000 /home/serve && \
    chmod -R 770 /home/serve && \
    # Applies to all users during build-time, default read-write access for groups
    echo "umask 007" >> /etc/profile.d/custom_umask.sh

# Switch to non-root user and configure shell
USER 1001
WORKDIR /home/serve
# Force login shell for all subsequent commands to source custom_umask.sh
SHELL ["/bin/bash", "-l", "-o", "pipefail", "-c"]

# Create test directory and a test python file with umask applied
RUN mkdir -p tests && \
    echo 'print("It works!")' > tests/test.py

# Create virtual environment and install Jupyter
RUN python3 -m venv .venv
RUN /home/serve/.venv/bin/pip install --upgrade pip \
    && /home/serve/.venv/bin/pip install --no-cache-dir \
    jupyter

# Install VS Code extensions
RUN code-server --install-extension ms-python.python \
    && code-server --install-extension ms-toolsai.jupyter

# Configure VS Code settings
ENV PATH="/home/serve/.venv/bin:${PATH}"
RUN mkdir -p /home/serve/.local/share/code-server/User \
    && echo '{"python.defaultInterpreterPath": "/home/serve/.venv/bin/python3"}' \
    > /home/serve/.local/share/code-server/User/settings.json

# Force login shell for all subsequent commands to source custom_umask.sh
# Start code-server with umask enforced during run-time
CMD ["/bin/bash", "-l", "-c", "umask 007 && /usr/bin/code-server --auth=none --bind-addr=0.0.0.0:1234 /home/serve/"]