FROM jupyter/minimal-notebook:latest

COPY tests/notebooks/basic.ipynb ./tests/basic.ipynb

USER root
RUN apt-get update && apt-get install curl -y --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN npm install npm@latest -g && \
    npm cache clean --force && \
    npm -v

USER $NB_UID
RUN pip install --no-cache-dir mlflow boto3 && \
    pip install --no-cache-dir --force-reinstall "minio==7.0.2"
