FROM pytorch/torchserve:latest

ENV MODEL_STORE=models
USER root 

COPY run_server.test.sh /home/model-server/run_server.sh

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -yq update \
    && apt-get -yq upgrade  \
    && rm -rf /var/lib/apt/lists/* \
    && chmod +x /home/model-server/run_server.sh

USER model-server

RUN mkdir -p model-store/$MODEL_STORE
WORKDIR /home/model-server
COPY tests/models/* model-store/$MODEL_STORE/
CMD ["/home/model-server/run_server.sh"]

