FROM python:3.8.16-slim-buster

RUN apt-get update && apt-get install -y python3 python3-pip && mkdir -p srv/tests
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . srv/tests
WORKDIR srv
# run the entrypoint (only when the image is instantiated into a container)
CMD python3 -m pytest