FROM python:3.8.16-slim-buster

RUN apt-get update && apt-get install -y python3 python3-pip && mkdir -p srv/tests
RUN apt install curl -y
WORKDIR srv
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . tests


CMD sleep 10; python -m pytest