FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV HOME_DIR=/home/rstudio-server
ENV DATA_DIR=$HOME_DIR
ENV RSTUDIO_VERSION=2022.12.0-353
ENV ARCH=amd64
ENV R_BIN=/usr/bin/R
#ENV RSTUDIO_CONFIG_DIR=$HOME_DIR/.config/rstudio
#ENV RSTUDIO_CONFIG_HOME=$HOME_DIR/.config/rstudio
#ENV RSTUDIO_DATA_HOME=$HOME_DIR/.local/share/rstudio


# Install R and RStudio Server dependencies
RUN apt-get update -qq\
  && apt-get install -yq \
    gdebi-core \
    dpkg-sig \
    libapparmor1 \
    libedit2 \
    libssl1.1 \
    lsb-release \
    psmisc \
    python3-setuptools \
    sudo \
    wget \
    libclang-dev \
    libcairo2-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libv8-dev \
    libjpeg-dev \
    libprotobuf-dev \
    protobuf-compiler \ 
    locales \ 
    r-base && \
    apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    

RUN locale-gen en_US.UTF-8 && \ 
    update-locale "LANG=en_US.UTF-8" && \
    gpg --keyserver keyserver.ubuntu.com --recv-keys 3F32EE77E331692F


RUN wget -q https://download2.rstudio.org/server/bionic/${ARCH}/rstudio-server-${RSTUDIO_VERSION}-${ARCH}.deb -O /tmp/rstudio-server.deb \ && \
    dpkg-sig --verify /tmp/rstudio-server.deb && \
    dpkg -i /tmp/rstudio-server.deb && \
    rm /tmp/rstudio-server.deb && \
    mkdir -p $HOME_DIR/.config/rstudio $HOME_DIR/.local/share/rstudio  && \ 
    chown -R rstudio-server:rstudio-server $HOME_DIR && \ 
    mkdir -p /etc/R

RUN echo "rsession-which-r=${R_BIN}" >$RSTUDIO_CONFIG_DIR/rserver.conf && \
    echo "auth-minimum-user-id=999"  >> $RSTUDIO_CONFIG_DIR/rserver.conf && \
    echo "server-daemonize=0" >> $RSTUDIO_CONFIG_DIR/rserver.conf && \
    echo "auth-validate-users=0" >> $RSTUDIO_CONFIG_DIR/rserver.conf && \
    echo "auth-none=1" >> $RSTUDIO_CONFIG_DIR/rserver.conf && \
    echo "server-data-dir=$DATA_DIR" && \
    echo "rsession-path=/usr/lib/rstudio-server/bin/rsession"

 RUN chown -R rstudio-server:rstudio-server /etc/rstudio \
      && chown -R rstudio-server:rstudio-server var/run/rstudio-server* \
      && chown -R rstudio-server:rstudio-server /usr/lib/rstudio-server \
      && chown -R rstudio-server:rstudio-server /var/lib/rstudio-server


RUN apt-get autoremove -yq && apt-get autoclean -yq && apt remove -y \
  python3-setuptools \
  wget \
  gdebi-core \
  dpkg-sig

# Set the working directory
WORKDIR $HOME_DIR

COPY start-rstudio-server.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start-rstudio-server.sh
USER rstudio-server

#CMD ["/usr/local/bin/start-rstudio-server.sh"] 

EXPOSE 8787
CMD ["rstudio-server start"]

