FROM pytorch/torchserve:latest

ENV MODEL_STORE=models
COPY tests/run_server.test.sh run_server.sh

USER root 
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get remove --purge python-setuptools \
    && apt-get -yq update \
    && apt-get -yq install --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -yq update \ 
    && apt-get upgrade -yq \
    && apt-get autoremove -yq && apt-get autoclean -yq \ 
    && pip install --upgrade pip torch torchvision torchtext torchaudio setuptools future 


RUN chmod +x run_server.sh
USER model-server
RUN mkdir -p model-store/$MODEL_STORE
COPY tests/models/* model-store/$MODEL_STORE/

ENTRYPOINT /home/model-server/run_server.sh
