# TODO: change to latest
FROM jupyter/minimal-notebook:latest

COPY tests/notebooks/basic.ipynb tests/basic.ipynb

USER root
RUN apt-get update && apt-get install curl -y

USER $NB_UID
RUN pip install mlflow boto3 && \
    pip install --force-reinstall "minio==7.0.2"
