FROM ubuntu:20.04

ENV USER=jovyan
ENV HOME=/home/$USER

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -yq update \
    && apt-get -yq install --no-install-recommends\
        curl \
        git \
        python3 \
        python3-pip \
        python3-distutils \ 
        gcc \
    && apt-get -yq upgrade  \
    && apt-get autoremove -yq && apt-get autoclean -yq \ 
    && rm -rf /var/lib/apt/lists/* 

RUN useradd -m $USER \
    && mkdir -p $HOME/mlruns \
    && chown -R $USER:$USER $HOME/mlruns

RUN pip install --upgrade --no-cache-dir pip setuptools \
    && pip install --no-cache-dir mlflow boto3 \
    && pip install --no-cache-dir --upgrade numba

WORKDIR $HOME 
USER $USER

COPY tests/mlrun_example.py mlrun_example.py
