name: Build and test rstudio image

on:
  push:
      branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build Inventory Image'
        run: |
            docker build -t ghcr.io/scilifelabdatacentre/rstudio:latest ./rstudio

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: 'ghcr.io/scilifelabdatacentre/rstudio:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: 'Run tests'
        env:
          IMAGE_NAME: ghcr.io/scilifelabdatacentre/rstudio:latest
        run: | 
          pip install -r ./rstudio/tests/requirements.txt
          python3 -m pytest ./rstudio