name: RStudio workflow

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build test image'
        run: |
            docker build -t ghcr.io/scilifelabdatacentre/rstudio:latest ./rstudio

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: 'ghcr.io/scilifelabdatacentre/rstudio:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          timeout: '30m0s'
          exit-code: '1'

      - name: 'Run tests'
        env:
          IMAGE_NAME: ghcr.io/scilifelabdatacentre/rstudio:latest
        run: | 
          pip install -r ./rstudio/tests/requirements.txt
          python3 -m pytest ./rstudio

  push: 
    if: | 
      github.ref == 'refs/heads/main' &&
      github.repository == 'scilifelabdatacentre/serve-images'
    needs: build_and_test
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    permissions:
      contents: readg
      packages: write
      
    steps:
      - name: 'Checkout github action'
        uses: actions/checkout@main

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build production image'
        run: |
            docker build -t ghcr.io/scilifelabdatacentre/rstudio:latest ./rstudio

      - name: Push to GHCR
        run: |
          docker push ghcr.io/scilifelabdatacentre/rstudio:latest