name: Deploy RStudio Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build Inventory Image'
        run: |
            docker build -t ghcr.io/scilifelabdatacentre/rstudio:latest ./rstudio

      - name: 'Run tests'
        env:
          IMAGE_NAME: ghcr.io/scilifelabdatacentre/rstudio:latest
        run: | 
          pip install -r ./rstudio/tests/requirements.txt
          python3 -m pytest ./rstudio

  push: 
    if: github.repository == 'scilifelabdatacentre/serve-images
    needs: build_and_test
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/scilifelabdatacentre/rstudio:latest