name: VS code workflow

on:
  push:
    paths:
      - "serve-vscode/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning  
        - debug
      tags:
        description: 'Manual run'
        required: false
        type: boolean
    

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Build test image
        run: |
            docker build -t test-image -f ./serve-vscode/Dockerfile.test ./serve-vscode

      - name: Display all HIGH vulnerabilities using Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'test-image'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'HIGH'
          timeout: '30m0s'
          exit-code: '0'

      - name: Fail only if CRITICAL vulnerabilities found using Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
            image-ref: 'test-image'
            format: 'table'
            vuln-type: 'os,library'
            severity: 'CRITICAL'
            timeout: '30m0s'
            # We are allowing it just for  now
            # please ensure it later
            # so that critical error is
            # handled gracefully
            exit-code: '0'

      - name: Run tests
        env:
          IMAGE_NAME: test-image
        run: | 
          pip install -r ./serve-vscode/requirements.txt
          python3 -m pytest ./serve-vscode

  push: 
    if: | 
      github.ref == 'refs/heads/main' &&
      github.repository == 'scilifelabdatacentre/serve-images'
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: 'Checkout github action'
      uses: actions/checkout@main

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/scilifelabdatacentre/serve-vscode
        tags: |
            type=raw,value={{date 'YYMMDD-HHmm' tz='Europe/Stockholm'}}

    - name: 'Login to GHCR'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Publish image to GHCR
      uses: docker/build-push-action@v3
      with:
        file: ./serve-vscode/Dockerfile
        context: ./serve-vscode
        push: true
        build-args: version=${{ github.ref_name }}
        tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/scilifelabdatacentre/serve-vscode:latest
        labels: ${{ steps.meta.outputs.labels }}
