name: Build and test torchserve image

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build Inventory Image'
        run: |
            docker build -t test-image -f ./torchserve/Dockerfile.test ./torchserve

      - name: 'Run tests'
        env:
          IMAGE_NAME: ghcr.io/scilifelabdatacentre/test-image:latest
        run: | 
          pip install -r ./torchserve/tests/requirements.txt
          python3 -m pytest ./torchserve