name: Deploy TorchServe Image to GHCR

on:
  push:
    branches:
      - main

jobs:

  BlackFormatting:
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Check code formatting with Black
        uses: psf/black@stable
        with:
          options: "-l 100 --check"
          src: "./torchserve"

  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build -t ghcr.io/scilifelabdatacentre/torchserve:latest ./torchserve
          docker push ghcr.io/scilifelabdatacentre/torchserve:latest