name: Build and test torchserve image

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build Inventory Image'
        run: |
            docker build -t test-image -f ./torchserve/Dockerfile.test ./torchserve

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: 'test-image'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: 'Run tests'
        env:
          IMAGE_NAME: test-image
        run: | 
          pip install -r ./torchserve/tests/requirements.txt
          python3 -m pytest ./torchserve