# Trivy scans of published images
# ---------------------------------
name: Trivy scans of published images

on:
  schedule:
    # Runs "At 4:30 UTC time daily Monday to Friday"
    - cron: "30 4 * * 1-5"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manual run'
        required: false
        type: boolean

jobs:
  scan:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on serve-jupyterlab:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/serve-jupyterlab:latest"
          format: "sarif"
          output: "trivy-results-jupyterlab-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab for jupyter-lab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-jupyterlab-latest.sarif"
          # assigns a category for results in the SARIF file
          category: trivy-jupyter-lab


      - name: Run Trivy vulnerability scanner on serve-rstudio:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/serve-rstudio:latest"
          format: "sarif"
          output: "trivy-results-rstudio-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab for rstudio
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-rstudio-latest.sarif"
          # assigns a category for results in the SARIF file
          category: trivy-rstudio


      - name: Run Trivy vulnerability scanner on serve-torchserve:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/serve-torchserve:latest"
          format: "sarif"
          output: "trivy-results-torchserve-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab for torchserver
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-torchserve-latest.sarif"
          # assigns a category for results in the SARIF file
          category: trivy-torchserver


      - name: Run Trivy vulnerability scanner on serve-mlflow:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/serve-mlflow:latest"
          format: "sarif"
          output: "trivy-results-mlflow-image-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab for mlflow
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-mlflow-image-latest.sarif"
          # assigns a category for results in the SARIF file
          category: trivy-mlflow-image
