# Trivy scans of published images
# ---------------------------------
name: Trivy scans of published images

on:
  schedule:
    # Runs "At 8:00 on every day-of-week from Monday through Friday"
    - cron: "30 7,15 * * 1-5"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manual run'
        required: false
        type: boolean

jobs:
  scan:
    permissions:
      contents: read
      security-events: write

    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on jupyter-lab:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/jupyter-lab:latest"
          format: "sarif"
          output: "trivy-results-jupyterlab-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab for jupyter-lab:latest
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-jupyterlab-latest.sarif"
          category: trivy


      - name: Run Trivy vulnerability scanner on rstudio:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/rstudio:latest"
          format: "sarif"
          output: "trivy-results-rstudio-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab for rstudio:latest
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-rstudio-latest.sarif"
          category: trivy


      - name: Run Trivy vulnerability scanner on torchserve:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/torchserve:latest"
          format: "sarif"
          output: "trivy-results-torchserve-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab for torchserver:latest
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-torchserve-latest.sarif"
          category: trivy


      - name: Run Trivy vulnerability scanner on mlflow-server:latest
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/scilifelabdatacentre/mlflow-server:latest"
          format: "sarif"
          output: "trivy-results-mlflowserver-latest.sarif"
          severity: "CRITICAL,HIGH"
          security-checks: 'vuln'
          timeout: '30m0s'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab for mlflowserver:latest
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-mlflowserver-latest.sarif"
          category: trivy
